from __future__ import annotations


JOINTS = [
    "Nose",
    "Left Eye",
    "Right Eye",
    "Left Ear",
    "Right Ear",
    "Left Shoulder",
    "Right Shoulder",
    "Left Elbow",
    "Right Elbow",
    "Left Wrist",
    "Right Wrist",
    "Left Hip",
    "Right Hip",
    "Left Knee",
    "Right Knee",
    "Left Ankle",
    "Right Ankle",
    "Neck",
    "Left Palm",
    "Right Palm",
    "Back",
    "Waist",
    "Left Foot",
    "Right Foot",
]


BODYWEIGHT_LABELS = [
    "스탠딩 사이드 크런치",
    "스탠딩 니업",
    "버피 테스트",
    "스텝 포워드 다이나믹 런지",
    "스텝 백워드 다이나믹 런지",
    "사이드 런지",
    "크로스 런지",
    "굿모닝",
    "라잉 레그 레이즈",
    "크런치",
    "바이시클 크런치",
    "시저크로스",
    "힙쓰러스트",
    "플랭크",
    "푸시업",
    "니푸쉬업",
    "Y - Exercise",
]


SKELETON_EDGES = [
    ("Nose", "Left Eye"),
    ("Nose", "Right Eye"),
    ("Left Eye", "Left Ear"),
    ("Right Eye", "Right Ear"),
    ("Neck", "Left Shoulder"),
    ("Neck", "Right Shoulder"),
    ("Left Shoulder", "Right Shoulder"),
    ("Left Shoulder", "Left Elbow"),
    ("Left Elbow", "Left Wrist"),
    ("Left Wrist", "Left Palm"),
    ("Right Shoulder", "Right Elbow"),
    ("Right Elbow", "Right Wrist"),
    ("Right Wrist", "Right Palm"),
    ("Neck", "Back"),
    ("Back", "Waist"),
    ("Waist", "Left Hip"),
    ("Waist", "Right Hip"),
    ("Left Hip", "Right Hip"),
    ("Left Hip", "Left Knee"),
    ("Left Knee", "Left Ankle"),
    ("Left Ankle", "Left Foot"),
    ("Right Hip", "Right Knee"),
    ("Right Knee", "Right Ankle"),
    ("Right Ankle", "Right Foot"),
]

